<?php

namespace Cesa\Bundle\AdministracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmpleadoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoTramiteRepository extends EntityRepository
{
    public function findTramites($empleado_id)
    {
        $em = $this->getEntityManager();

        $consulta = $em->createQuery('
            SELECT et
            FROM AdministracionBundle:EmpleadoTramite et
            WHERE et.empleado = :id AND et.estado = :estado
            ');
        $consulta->setParameter('id', $empleado_id);
        $consulta->setParameter('estado', 1);


        return $consulta->getResult();
    }

    public function findTramiteEmp($tramite_id)
    {
        $em = $this->getEntityManager();

        $consulta = $em->createQuery('
            SELECT et
            FROM AdministracionBundle:EmpleadoTramite et
            WHERE et.tramite = :id AND et.estado = :estado
            ');
        $consulta->setParameter('id', $tramite_id);
        $consulta->setParameter('estado', 1);


        return $consulta->getSingleResult();
    }


}
