<?php

namespace Cesa\Bundle\TramiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteRepository extends EntityRepository
{
}
