<?php

namespace Cesa\Bundle\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
    public function consultan($parametro)
    {
        $qb = $this->createQueryBuilder(
            'SELECT c
            FROM CLienteBundle:Cliente as c
            WHERE c.nombres LIKE :parametro'
        )->setParameter('parametro', $parametro)
        ;

    }
}