parameters:
#    administracion.example.class: Cesa\Bundle\AdministracionBundle\Example

services:
#    administracion.example:
#        class: %administracion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
